% -------------------------------------------------------------------
%  Generated by MATLAB on 13-Oct-2022 13:16:11
%  MATLAB version: 9.12.0.2039608 (R2022a) Update 5
% -------------------------------------------------------------------
saveVarsMat = load('DroneMk1_DataFile1.mat');

Variance = 0.001;

randomness_variance = 1E-5;

smiData = saveVarsMat.smiData; % <1x1 struct> unsupported class at smiData.RigidTransform(1).ID

clear saveVarsMat;
